# Generated by Django 4.0 on 2023-01-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=10)),
                ('Author', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=10)),
                ('Author', models.CharField(max_length=10)),
                ('Publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='request_for_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=10)),
                ('Author', models.CharField(max_length=10)),
            ],
        ),
    ]
